spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

security.token.secret=14609ba80aff2d3e2e846504c2b9c294afa18147
security.token.secret.candidate=330f0ec44e32c20041335dfbcfb19b727dc6e8da

sonar.token=sqp_1de1c409c79b309e1ff4baddbbb60a12f12e0d70

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true